enum EmailsTypes {
    GET_EMAILS_STARTED = 'GET_EMAILS_STARTED',
    GET_EMAILS_SUCCESS = 'GET_EMAILS_SUCCESS',
    GET_EMAILS_ERROR = 'GET_EMAILS_ERROR',

    CREATE_EMAILS_STARTED = 'CREATE_EMAILS_STARTED',
    CREATE_EMAILS_SUCCESS = 'CREATE_EMAILS_SUCCESS',
    CREATE_EMAILS_ERROR = 'CREATE_EMAILS_ERROR',

    UPDATE_EMAILS_STARTED = 'UPDATE_EMAILS_STARTED',
    UPDATE_EMAILS_SUCCESS = 'UPDATE_EMAILS_SUCCESS',
    UPDATE_EMAILS_ERROR = 'UPDATE_EMAILS_ERROR',

    DELETE_EMAILS_STARTED = 'DELETE_EMAILS_STARTED',
    DELETE_EMAILS_SUCCESS = 'DELETE_EMAILS_SUCCESS',
    DELETE_EMAILS_ERROR = 'DELETE_EMAILS_ERROR',
}

export default EmailsTypes;